### ISSUE TITLE
make command not working

### ISSUE THREAD

**Issue by ghost** [Phantas0s/mouseless-book-behind-scene#1]
Hi, i was trying to compile the book, but every time i run the make command it throw this output

`bash
Error running filter pandoc-latex-enviroment:
Could not find executable pandox-latex-enviroment
make *** [Makefile:73: output/book.pdf] Error 83
`

I've already installed pandoc, which other dependency do i need to make the file?

**Comment by Phantas0s** [comment]
Hi

You need to install [pandoc-latex-environment](https://github.com/chdemko/pandoc-latex-environment). 

It's not needed if you don't want notice boxes though (you can find [more information about that there](https://github.com/Wandmalfarbe/pandoc-latex-template/issues/115)) . In that case, simply delete the line `--filter pandoc-latex-environment \` in the Makefile.

**Comment by ghost** [comment]
Hi, me again, i was able to instal pandoc-latex-enviroment but now i've  issues with compiling making reference to --pdf-engine. Would you mind to write a compile guide in the readme?

**Comment by Phantas0s** [comment]
Hi,

There is nothing to do normally except installing what I put on the README and run the makefile. After that it depends what you've installed, what distro you use, and what markdown you're trying to compile. Did you install Tex live?

I can help you if you want but it would be nice to create a new issue and explain a bit more your problem :)
